### ISSUE TITLE
Alias in cliOptions must be single character

### ISSUE THREAD

**Issue by Japiejo28** [ngneat/transloco-keys-manager#19]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

In version 1.3.0 the project CLI option is added in cliOptions.js. It has a alias pr ( 2 characters ) but the command-line-args package gives a error there: INVALID_DEFINITIONS: Invalid option definition: an alias must be a single character.

## Expected behavior

The alias needs to have a single character alias, now the transloco-keys-manager command will trow a error and will nowt work

## Minimal reproduction of the problem with instructions

ng g @ngneat/transloco:keys-manager (version 1.3.0)

run any transloco-keys-manager command

you will get a error INVALID_DEFINITIONS: Invalid option definition: an alias must be a single character.

**Comment by shaharkazaz** [comment]
@Japiejo28 Should be ok in v1.3.1, can you verify?

**Comment by Japiejo28** [comment]
@shaharkazaz  For me it works now thanks.

**Comment by ronnetzer** [comment]
@shaharkazaz thanks for the quick fix, I'm getting a different error now when trying to use --project flag (the project exists in angular.json and also sourceRoot is defined..)

```bash
TypeError: Cannot destructure property `sourceRoot` of 'undefined' or 'null'.
    at Object.resolveProjectPath (/Users/ronnetzer/Documents/Projects/paypo-monorepo-client/node_modules/@ngneat/transloco-keys-manager/helpers/resolveProjectPath.js:1:374)
    at Object.resolveConfig (/Users/ronnetzer/Documents/Projects/paypo-monorepo-client/node_modules/@ngneat/transloco-keys-manager/helpers/resolveConfig.js:1:508)
    at Object.findMissingKeys (/Users/ronnetzer/Documents/Projects/paypo-monorepo-client/node_modules/@ngneat/transloco-keys-manager/keysDetective.js:1:553)
    at Object.<anonymous> (/Users/ronnetzer/Documents/Projects/paypo-monorepo-client/node_modules/@ngneat/transloco-keys-manager/index.js:2:744)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
```

this is my transloco.config.js
```javascript
module.exports = {
  "langs": [
    "en",
    "he"
  ],
  "keysManager": {},
  "rootTranslationsPath": "src/assets/i18n/"
};
```

**Comment by shaharkazaz** [comment]
@ronnetzer what version are you using? can you try 1.3.2?

**Comment by ronnetzer** [comment]
i've used 1.3.1. 1.3.2 seems to work good
