### ISSUE TITLE
transloco-keys-manager extract Invalid regular expression

### ISSUE THREAD

**Issue by RFMV34** [ngneat/transloco-keys-manager#4]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

When I run transloco-keys-manager extract I get following message:
```
> translation@0.0.0 i18n:extract C:\Users\gulanf\Documents\translation
> transloco-keys-manager extract

C:\Users\gulanf\Documents\translation\node_modules\@ngneat\transloco-keys-manager\regexs.js:1
(function (exports, require, module, __filename, __dirname) { "use strict";Object.defineProperty(exports,"__esModule",{value:!0});const sanitizeForRegex_1=require("./helpers/sanitizeForRegex");exports.regexs={templateKey:e=>new Re
gExp(`${e}\\((?![^,)+]*\\+)('|")(?<key>[^)"']*?)\\1`,"g"),directive:()=>new RegExp("\\stransloco\\s*=\\s*(\"|')(?<key>[^]+?)\\1","g"),directiveTernary:()=>new RegExp("\\s\\[transloco\\]\\s*=\\s*(\"|')[^\"'?]*\\?(?<key>[^]+?)\\1","
g"),pipe:()=>/(?:(?:\{\{(?![^^}\|+]*\+)[^}\|'"]*)|(?:\[[^\]]*\]=(?:"|')(?![^'"+]*\+)[^'"]*))('|")(?<key>[^'"[>=]*?)\1[^'"\|[}]*(?:('|")(?<key2>[^"'[>]*?)\3)?[^\|}>[]*?\|[^}>]*?transloco/g,fileLang:e=>new RegExp(`${sanitizeForRegex
_1.sanitizeForRegex(e)}\\/(?:(?<scope>(?:[^\\.]*)*)\\/)?(?<fileLang>[^./]*)\\.json`),serviceInjection:/[^]*(?=(?:private|protected|public)\s+(?<serviceName>[^,:()]+)\s*:\s*(?:TranslocoService\s*(?:,|\))))[^]*/,translationCalls:e=>
{const s

SyntaxError: Invalid regular expression: /[^]*(?=(?:private|protected|public)\s+(?<serviceName>[^,:()]+)\s*:\s*(?:TranslocoService\s*(?:,|\))))[^]*/: Invalid group
    at Object.<anonymous> (C:\Users\gulanf\Documents\translation\node_modules\@ngneat\transloco-keys-manager\regexs.js:1:194)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\gulanf\Documents\translation\node_modules\@ngneat\transloco-keys-manager\keysBuilder\getStructuralDirectiveBasedKeys.js:1:146)
    at Module._compile (module.js:653:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! translation@0.0.0 i18n:extract: `transloco-keys-manager extract`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the translation@0.0.0 i18n:extract script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\gulanf\AppData\Roaming\npm-cache\_logs\2019-11-18T10_28_04_726Z-debug.log
```

And debug log contains: 
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'i18n:extract' ]
2 info using npm@6.4.1
3 info using node@v8.16.1
4 verbose run-script [ 'prei18n:extract', 'i18n:extract', 'posti18n:extract' ]
5 info lifecycle translation@0.0.0~prei18n:extract: translation@0.0.0
6 info lifecycle translation@0.0.0~i18n:extract: translation@0.0.0
7 verbose lifecycle translation@0.0.0~i18n:extract: unsafe-perm in lifecycle true
8 verbose lifecycle translation@0.0.0~i18n:extract: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\gulanf\Documents\translation\node_modules\.bin;C:\Users\gulanf\Documents\translation\node_modules\.bin;C:\ProgramData\DockerDesktop\version-bin;C:\Program Files\Docker\Docker\Resources\bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\PuTTY\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Programs\apache-maven-3.6.2\bin;C:\ProgramData\chocolatey\bin;C:\Users\gulanf\.windows-build-tools\python27\;C:\Users\gulanf\AppData\Local\Microsoft\WindowsApps;C:\Users\gulanf\AppData\Roaming\npm;C:\Exercism;C:\Users\gulanf\AppData\Local\Microsoft\WindowsApps;C:\tools\dart-sdk\bin;C:\Users\gulanf\AppData\Roaming\Pub\Cache\bin;
9 verbose lifecycle translation@0.0.0~i18n:extract: CWD: C:\Users\gulanf\Documents\translation
10 silly lifecycle translation@0.0.0~i18n:extract: Args: [ '/d /s /c', 'transloco-keys-manager extract' ]
11 silly lifecycle translation@0.0.0~i18n:extract: Returned: code: 1  signal: null
12 info lifecycle translation@0.0.0~i18n:extract: Failed to exec i18n:extract script
13 verbose stack Error: translation@0.0.0 i18n:extract: `transloco-keys-manager extract`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:915:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid translation@0.0.0
15 verbose cwd C:\Users\gulanf\Documents\translation
16 verbose Windows_NT 10.0.18362
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "i18n:extract"
18 verbose node v8.16.1
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error translation@0.0.0 i18n:extract: `transloco-keys-manager extract`
22 error Exit status 1
23 error Failed at the translation@0.0.0 i18n:extract script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

## Expected behavior

Run transloco-keys-manager extract and get translations keys.

## Minimal reproduction of the problem with instructions

For bug reports please provide the _STEPS TO REPRODUCE_ and if possible a _MINIMAL DEMO_ of the problem, for that you could use our [stackblitz example](https://stackblitz.com/edit/transloco-example)
```

## What is the motivation / use case for changing the behavior?

I want to use this lib in my project.

## Environment

<pre><code>
Angular version: 7.3.9

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.16.1 
- Platform:  Windows 

Others:

</code></pre>

**Comment by shaharkazaz** [comment]
@RFMV34 Hey, 
You are using an old node version, this regex is using a feature that is supported from node 10 and above.
To resolve this please upgrade your node version.

I'll add it to the docs 🙂

**Comment by RFMV34** [comment]
The upgrade is not possible for me currently, but thanks :)
