### ISSUE TITLE
"Cannot read property 'project' of undefined" when running with webpack plugin

### ISSUE THREAD

**Issue by dorthrithil** [ngneat/transloco-keys-manager#55]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Running `ng serve --extra-webpack-config webpack-dev.config.js` throws:

```
[error] TypeError: Cannot read property 'project' of undefined
    at Object.resolveConfig (/Users/fengelmann/developement/labapp/client/node_modules/@ngneat/transloco-keys-manager/helpers/resolveConfig.js:1:597)
    at new TranslocoExtractKeysWebpackPlugin (/Users/fengelmann/developement/labapp/client/node_modules/@ngneat/transloco-keys-manager/webpack-plugin.js:1:722)
    at Object.<anonymous> (/Users/fengelmann/developement/labapp/client/webpack-dev.config.js:4:13)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1040:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.transforms.<computed> [as webpackConfiguration] (/Users/fengelmann/developement/labapp/client/node_modules/ngx-build-plus/src/utils/index.js:56:38)
    at setup (/Users/fengelmann/developement/labapp/client/node_modules/@angular-devkit/build-angular/src/dev-server/index.js:115:46)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

## Expected behavior

No error.

## Minimal reproduction of the problem with instructions

- Setup an angular project with transloco
- Add the keys-manager `ng g @ngneat/transloco:keys-manager` and accept webpack plugin setup
- Run the above command 

## Environment

<pre><code>
Angular version: 9.0.7
Transloco versio: 2.19.1
 
For Tooling issues:
- Node version: v13.7.0
- Platform:  Mac

**Comment by shaharkazaz** [comment]
@dorthrithil Seems to be working for me... can you please create a reproduction repo and share it? 🙂

**Comment by shaharkazaz** [comment]
@dorthrithil feel free to reopen once you provide a reproduction 🙂
